root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  data-organization/00_ann_format_navi/08_supervisely_format_volume/: data-organization/Annotation-JSON-format/08_Supervisely_format_volume.md
  data-organization/00_ann_format_navi/08_supervisely_format_volume: data-organization/Annotation-JSON-format/08_Supervisely_format_volume.md
  data-organization/00_ann_format_navi: data-organization/Annotation-JSON-format/00_ann_format_navi.md
  getting-started/connect-your-computer/agents/ami: agents/ami/README.md
  getting-started/connect-your-computer/agents/add_delete_node: agents/add_delete_node/add_delete_node.md
  enterprise/installation: enterprise/installation/README.md
  enterprise/installation/: enterprise/installation/README.md
  enterprise-edition/installation: enterprise/installation/README.md
  enterprise-edition/installation/: enterprise/installation/README.md
  enterprise/post-installation: enterprise/post-installation/README.md
  enterprise/post-installation/: enterprise/post-installation/README.md
  enterprise/advanced-tuning/index-1: enterprise/sso/README.md
  enterprise-edition/advanced-tuning/index-1: enterprise/sso/README.md
  cluster/overview: getting-started/connect-your-computer/README.md
  cluster/overview/: getting-started/connect-your-computer/README.md
  ann_format: data-organization/Annotation-JSON-format/00_ann_format_navi.md
  ann_format/: data-organization/Annotation-JSON-format/00_ann_format_navi.md
  customization/agents/status: agents/status_and_troubleshooting/status.md
  customization/agents/status/: agents/status_and_troubleshooting/status.md
  customization/agents: getting-started/connect-your-computer/README.md
  customization/agents/: getting-started/connect-your-computer/README.md
  getting-started/first-steps: getting-started/How-to-import.md
  getting-started/first-steps/: getting-started/How-to-import.md
  labeling/editors/images: labeling/images/README.md
  labeling/editors/images/: labeling/images/README.md
  customization/agents/agent-storage: agents/agent-storage/agent-storage.md
  data-organization/quality-assurance-and-statistics: data-organization/project-dataset/quality-assurance-and-statistics/README.md
  data-organization/quality-assurance-and-statistics/practical-applications-of-statistics/: data-organization/project-dataset/quality-assurance-and-statistics/practical-applications-of-statistics.md
  data-organization/quality-assurance-and-statistics/practical-applications-of-statistics: data-organization/project-dataset/quality-assurance-and-statistics/practical-applications-of-statistics.md